# Generated by Django 6.0.5 on 2026-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                ("dept", models.CharField(max_length=100, verbose_name="部署名")),
                ("role", models.CharField(max_length=100, verbose_name="役職")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="メールアドレス"),
                ),
                ("joined_date", models.DateField(verbose_name="入社日")),
            ],
            options={
                "verbose_name": "社員",
                "verbose_name_plural": "社員",
            },
        ),
    ]
